# We set the version of the file
version: '3.1'
# This part is explained below the file
services:
  microservice:
    image: mock_service  # <-- build and tag mock_service docker image 
    command: bundle exec rackup --host 0.0.0.0
    ports:
      - "9292:9292"
    volumes:
      - .:/app:cached
      - tmp:/app/tmp
volumes:
  tmp:

